trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.14.0'
  displayName: 'Install Node.js'

- script: yarn
  displayName: 'Install dependencies'

- script: yarn lint
  displayName: 'Lint app'

- script: yarn electron:build
  displayName: 'Build app'
