export default {
  mutations: {
    ITEM_DATA_ADD: 'ITEM_DATA_ADD',
    ITEM_DATA_SIZE_WIDTH_CHANGE: 'ITEM_DATA_SIZE_WIDTH_CHANGE',
    ITEM_DATA_SIZE_HEIGHT_CHANGE: 'ITEM_DATA_SIZE_HEIGHT_CHANGE',

    SETTINGS_ICON_VISIBLE_CHANGE: 'SETTINGS_ICON_VISIBLE_CHANGE',

    ITEM_EDIT_MODE_CHANGE: 'ITEM_EDIT_MODE_CHANGE',
  },
};
