export default {
  mutations: {
    ITEM_DATA_ADD: 'ITEM_DATA_ADD',
    ITEM_DATA_SIZE_WIDTH_CHANGE: 'ITEM_DATA_SIZE_WIDTH_CHANGE',
    ITEM_DATA_SIZE_HEIGHT_CHANGE: 'ITEM_DATA_SIZE_HEIGHT_CHANGE',
  },
};
