export default {
  mutations: {
    UPDATE_ITEM_SIZE_FROM_CURRENT_TAB: 'UPDATE_ITEM_SIZE_FROM_CURRENT_TAB',
    UPDATE_ITEM_FROM_CURRENT_TAB: 'UPDATE_ITEM_FROM_CURRENT_TAB',
    ADD_ITEM_TO_CURRENT_TAB: 'ADD_ITEM_TO_CURRENT_TAB',
    REMOVE_ITEM_FROM_CURRENT_TAB: 'REMOVE_ITEM_FROM_CURRENT_TAB',

    ADD_TAB: 'ADD_TAB',

    SET_SETTINGS: 'SET_SETTINGS',

    CONFIG_DIR_SET: 'CONFIG_DIR_SET',

    ITEM_EDIT_MODE_CHANGE: 'ITEM_EDIT_MODE_CHANGE',
    CHANGE_SETTINGS_VISIBLE_CHANGE: 'CHANGE_SETTINGS_VISIBLE_CHANGE',
  },
};
